---
- name: Create secure user with sudo and SSH access
  hosts: target
  become: yes
  vars:
    secure_user: secureadmin
    ssh_pub_key: "ssh-rsa AAAAB3...your_public_key_here"

  tasks:
    - name: Add user
      user:
        name: "{{ secure_user }}"
        shell: /bin/bash
        groups: sudo
        state: present
        create_home: yes

    - name: Add authorized key
      authorized_key:
        user: "{{ secure_user }}"
        state: present
        key: "{{ ssh_pub_key }}"
