---
- name: "CLEANUP: Undo Network Security & Service Management Hardening"
  hosts: all
  become: yes
  tasks:
    # Restore Network Security Settings to defaults
    - name: "Restore Network Security Settings to defaults"
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
        sysctl_file: /etc/sysctl.d/99-security.conf
      loop:
        - { name: "net.ipv4.ip_forward", value: "1" } # Re-enable forwarding
        - { name: "net.ipv4.tcp_syncookies", value: "1" } # Keep enabled (good default)
        - { name: "net.ipv4.conf.all.accept_redirects", value: "1" }
        - { name: "net.ipv4.conf.default.accept_redirects", value: "1" }
        - { name: "net.ipv4.conf.all.send_redirects", value: "1" }
        - { name: "net.ipv4.conf.default.send_redirects", value: "1" }
        - { name: "net.ipv4.conf.all.accept_source_route", value: "1" }
        - { name: "net.ipv4.conf.default.accept_source_route", value: "1" }
        - { name: "net.ipv4.icmp_echo_ignore_broadcasts", value: "0" }
        - { name: "net.ipv4.icmp_ignore_bogus_error_responses", value: "0" }
      register: network_cleanup

    # Remove custom sysctl file
    - name: "Remove custom security sysctl configuration"
      file:
        path: /etc/sysctl.d/99-security.conf
        state: absent
      register: sysctl_file_removed

    # Restore Password Policy to defaults
    - name: "Restore password aging policy to defaults"
      lineinfile:
        path: /etc/login.defs
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        backup: yes
      loop:
        - { regexp: "^PASS_MIN_DAYS", line: "PASS_MIN_DAYS 0" } # Default: 0
        - { regexp: "^PASS_MAX_DAYS", line: "PASS_MAX_DAYS 99999" } # Default: 99999
        - { regexp: "^PASS_MIN_LEN", line: "PASS_MIN_LEN 5" } # Default: 5
        - { regexp: "^PASS_WARN_AGE", line: "PASS_WARN_AGE 7" } # Keep 7 (reasonable)
      register: password_policy_restored

    # Remove custom log rotation configuration
    - name: "Remove custom security log rotation"
      file:
        path: /etc/logrotate.d/security-logs
        state: absent
      register: logrotate_removed

    # Disable and reset UFW firewall
    - name: "Disable UFW firewall"
      ufw:
        state: disabled
      register: ufw_disabled
      ignore_errors: yes

    - name: "Reset UFW to factory defaults"
      ufw:
        state: reset
      register: ufw_reset
      ignore_errors: yes

    # Note: We don't re-enable risky services as they should stay disabled for security
    # Note: We keep logging services running as they're essential

    - name: "Reload sysctl settings"
      command: sysctl --system
      register: sysctl_reloaded

    - name: "Display Cleanup Results"
      debug:
        msg: |
          =================== HARDENING 2 CLEANUP COMPLETE ===================

          NETWORK SECURITY RESTORED:
          - IP Forwarding: {{ 'ENABLED' if network_cleanup.changed else 'ALREADY DEFAULT' }}
          - ICMP Redirects: {{ 'ALLOWED' if network_cleanup.changed else 'ALREADY DEFAULT' }}
          - Source Routing: {{ 'ENABLED' if network_cleanup.changed else 'ALREADY DEFAULT' }}
          - ICMP Broadcast: {{ 'RESPONDING' if network_cleanup.changed else 'ALREADY DEFAULT' }}
          - Custom sysctl file: {{ 'REMOVED' if sysctl_file_removed.changed else 'NOT FOUND' }}

          PASSWORD POLICY RESTORED:
          - Min password age: {{ 'RESTORED (0 days)' if password_policy_restored.changed else 'ALREADY DEFAULT' }}
          - Max password age: {{ 'RESTORED (99999 days)' if password_policy_restored.changed else 'ALREADY DEFAULT' }}
          - Min password length: {{ 'RESTORED (5 chars)' if password_policy_restored.changed else 'ALREADY DEFAULT' }}

          LOGGING:
          - Custom log rotation: {{ 'REMOVED' if logrotate_removed.changed else 'NOT FOUND' }}
          - System logging: KEPT RUNNING (Essential service)

          FIREWALL:
          - UFW status: {{ 'DISABLED' if ufw_disabled.changed else 'ALREADY DISABLED' }}
          - UFW rules: {{ 'RESET' if ufw_reset.changed else 'ALREADY CLEAN' }}

          SERVICES:
          - Risky services: LEFT DISABLED (Security best practice)

          SYSTEM:
          - Sysctl settings: {{ 'RELOADED' if sysctl_reloaded.rc == 0 else 'RELOAD FAILED' }}

          ==========================================================
