---
- name: Install and Configure fail2ban
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Update package cache (Ubuntu/Debian)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update package cache (CentOS/RHEL)
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Install fail2ban (Ubuntu/Debian)
      apt:
        name: fail2ban
        state: present
      when: ansible_os_family == "Debian"

    - name: Install fail2ban (CentOS/RHEL)
      yum:
        name: fail2ban
        state: present
      when: ansible_os_family == "RedHat"

    - name: Create fail2ban SSH jail configuration
      copy:
        dest: /etc/fail2ban/jail.d/ssh.conf
        content: |
          [ssh]
          enabled = true
          port = ssh
          filter = sshd
          logpath = /var/log/auth.log
          maxretry = 3
          bantime = 3600
          findtime = 600
        mode: "0644"
        owner: root
        group: root

    - name: Start and enable fail2ban service
      systemd:
        name: fail2ban
        state: started
        enabled: yes

    - name: Verify fail2ban is running
      systemd:
        name: fail2ban
      register: fail2ban_status

    - name: Report installation success
      debug:
        msg: |
          ===========================================
          FAIL2BAN HARDENING COMPLETE
          ===========================================
          Service Status: {{ fail2ban_status.status.ActiveState }}
          Service Enabled: {{ fail2ban_status.status.UnitFileState }}
          SSH Jail: Configured with 3 retry limit
          Ban Time: 1 hour
          ===========================================
