---
- name: Safe Linux Hardening - Basic Security Measures
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install fail2ban for intrusion prevention
      package:
        name: fail2ban
        state: present

    - name: Start and enable fail2ban service
      systemd:
        name: fail2ban
        state: started
        enabled: yes

    - name: Create custom fail2ban SSH jail configuration
      copy:
        content: |
          [sshd]
          enabled = true
          port = ssh
          logpath = /var/log/auth.log
          maxretry = 5
          bantime = 3600
          findtime = 600
        dest: /etc/fail2ban/jail.d/ssh.conf
        backup: yes
      notify: restart fail2ban

    - name: Set proper permissions on /etc/passwd
      file:
        path: /etc/passwd
        mode: "0644"
        owner: root
        group: root

    - name: Set proper permissions on /etc/shadow
      file:
        path: /etc/shadow
        mode: "0640"
        owner: root
        group: shadow

    - name: Create security banner file
      copy:
        content: |
          **************************************************************************
          WARNING: This system is for authorized users only.
          All activities are monitored and logged.
          **************************************************************************
        dest: /etc/issue.net
        mode: "0644"
        owner: root
        group: root

    - name: Configure SSH banner (without breaking password auth)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?Banner"
        line: "Banner /etc/issue.net"
        backup: yes
      notify: reload sshd

    - name: Disable unused network protocols
      lineinfile:
        path: /etc/modprobe.d/blacklist-rare-network.conf
        line: "{{ item }}"
        create: yes
      loop:
        - "install dccp /bin/true"
        - "install sctp /bin/true"
        - "install rds /bin/true"
        - "install tipc /bin/true"

    - name: Set kernel parameters for network security
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop:
        - { name: "net.ipv4.conf.all.send_redirects", value: "0" }
        - { name: "net.ipv4.conf.default.send_redirects", value: "0" }
        - { name: "net.ipv4.conf.all.accept_redirects", value: "0" }
        - { name: "net.ipv4.conf.default.accept_redirects", value: "0" }
        - { name: "net.ipv4.icmp_ignore_bogus_error_responses", value: "1" }

    - name: Install and configure automatic security updates
      package:
        name: unattended-upgrades
        state: present
      when: ansible_os_family == "Debian"

    - name: Configure unattended upgrades
      copy:
        content: |
          Unattended-Upgrade::Allowed-Origins {
              "${distro_id}:${distro_codename}-security";
          };
          Unattended-Upgrade::AutoFixInterruptedDpkg "true";
          Unattended-Upgrade::MinimalSteps "true";
          Unattended-Upgrade::Remove-Unused-Dependencies "true";
          Unattended-Upgrade::Automatic-Reboot "false";
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        backup: yes
      when: ansible_os_family == "Debian"

  handlers:
    - name: restart fail2ban
      systemd:
        name: fail2ban
        state: restarted

    - name: reload sshd
      systemd:
        name: sshd
        state: reloaded
