---
- name: Cloud Hardening Test Playbook
  hosts: all
  gather_facts: yes
  become: no

  vars:
    test_message: "Cloud Hardening Playbook Test - Connection Successful!"
    timestamp: "{{ ansible_date_time.iso8601 }}"

  tasks:
    - name: Display welcome message
      debug:
        msg:
          - "========================================="
          - "{{ test_message }}"
          - "========================================="
          - "Target Host: {{ inventory_hostname }}"
          - "Operating System: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Architecture: {{ ansible_architecture }}"
          - "Test executed at: {{ timestamp }}"
          - "Ansible Version: {{ ansible_version.full }}"
          - "========================================="

    - name: Test basic connectivity
      ping:
      register: ping_result

    - name: Confirm ping success
      debug:
        msg: "✓ Ping test successful - Host is reachable"
      when: ping_result is succeeded

    - name: Display system information
      debug:
        msg:
          - "System Details:"
          - "  - Hostname: {{ ansible_hostname }}"
          - "  - FQDN: {{ ansible_fqdn }}"
          - "  - IP Address: {{ ansible_default_ipv4.address | default('N/A') }}"
          - "  - Memory: {{ (ansible_memtotal_mb/1024) | round(1) }}GB"
          - "  - CPU Cores: {{ ansible_processor_vcpus }}"
          - "  - Uptime: {{ ansible_uptime_seconds | int // 3600 }}h {{ (ansible_uptime_seconds | int % 3600) // 60 }}m"

    - name: Test file operations capability
      copy:
        content: |
          Cloud Hardening Test File
          Created: {{ timestamp }}
          Host: {{ inventory_hostname }}
        dest: /tmp/cloud_hardening_test.txt
        mode: "0644"
      register: file_test

    - name: Confirm file creation
      debug:
        msg: "✓ File operations test successful - Can create files"
      when: file_test is succeeded

    - name: Cleanup test file
      file:
        path: /tmp/cloud_hardening_test.txt
        state: absent

    - name: Final success message
      debug:
        msg:
          - "========================================="
          - "🎉 ALL TESTS PASSED! 🎉"
          - "Your cloud hardening playbook environment"
          - "is ready for production use."
          - "========================================="
