---
- name: Enable Password Authentication
  hosts: all
  become: yes
  gather_facts: yes

  vars_prompt:
    - name: root_password
      prompt: "Enter new root password"
      private: yes
      confirm: yes

  tasks:
    - name: Set root password
      user:
        name: root
        password: "{{ root_password | password_hash('sha512') }}"

    - name: Enable password authentication in SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication yes"
        backup: yes
      notify: restart ssh

    - name: Ensure public key authentication remains enabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PubkeyAuthentication"
        line: "PubkeyAuthentication yes"
        backup: yes
      notify: restart ssh

    - name: Enable challenge response authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?ChallengeResponseAuthentication"
        line: "ChallengeResponseAuthentication yes"
        backup: yes
      notify: restart ssh

    - name: Verify SSH configuration
      shell: sshd -t
      register: ssh_config_test

    - name: Display SSH config test result
      debug:
        msg: "SSH configuration is valid"
      when: ssh_config_test.rc == 0

  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted
