---
- name: CIS Cloud Hardening - Aligned with Audit
  hosts: all
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3.10
    
  tasks:
    # CIS 1.1.1 - Set SSH Banner
    - name: Ensure /etc/issue.net exists with proper banner
      copy:
        dest: /etc/issue.net
        content: "Authorized access only. Unauthorized use is prohibited."
        owner: root
        group: root
        mode: "0644"

    - name: Configure SSH to use banner file
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?Banner"
        line: "Banner /etc/issue.net"
        create: yes
      notify: Restart SSH

    # CIS 1.3.1 - MOTD content
    - name: Ensure /etc/motd contains welcome message
      copy:
        dest: /etc/motd
        content: "Welcome to a secured system. Unauthorized access is prohibited."
        owner: root
        group: root
        mode: "0644"

    # CIS 3.1.1 - Disable IP forwarding
    - name: Set net.ipv4.ip_forward = 0 (runtime)
      sysctl:
        name: net.ipv4.ip_forward
        value: '0'
        state: present
        reload: yes

    - name: Set net.ipv4.ip_forward = 0 in /etc/sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        regexp: '^net.ipv4.ip_forward'
        line: 'net.ipv4.ip_forward = 0'
        state: present

    # CIS 4.1.1.1 - Install auditd
    - name: Ensure auditd is installed
      package:
        name: auditd
        state: present

    - name: Ensure auditd is enabled and started
      service:
        name: auditd
        enabled: yes
        state: started

    # CIS 5.2.4 - Disable SSH root login
    - name: Ensure SSH root login is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin no"
        state: present
      notify: Restart SSH

    # CIS 5.2.5 - Set SSH log level
    - name: Set SSH LogLevel to VERBOSE
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?LogLevel"
        line: "LogLevel VERBOSE"
        state: present
      notify: Restart SSH

    # CIS 6.1.10 - Remove world-writable permissions
    - name: Find and fix world-writable files
      shell: |
        find / -xdev -type f -perm -0002 -exec chmod o-w {} \;
      args:
        warn: false

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted

