---
- name: Configure UFW firewall
  hosts: target
  become: yes
  tasks:
    - name: Allow SSH
      ufw:
        rule: allow
        name: OpenSSH

    - name: Allow HTTP
      ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled
        enabled: yes
