---
- name: CIS Benchmark Audit - pfSense
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Check CIS 1.1.1 - SSH Banner
      shell: grep '^Banner /etc/issue.net' /etc/ssh/sshd_config || echo "NOT SET"
      register: ssh_banner
      changed_when: false

    - name: Report SSH Banner compliance
      debug:
        msg: >
          CIS 1.1.1 - SSH Banner: {{ '✅ COMPLIANT' if 'Banner /etc/issue.net' in ssh_banner.stdout else '❌ NOT COMPLIANT' }}

    - name: Check CIS 1.3 - MOTD
      shell: cat /etc/motd || echo "MOTD file not found"
      register: motd
      changed_when: false

    - name: Report MOTD compliance
      debug:
        msg: >
          CIS 1.3 - MOTD Content: {{ '✅ COMPLIANT' if motd.stdout|length > 0 else '❌ NOT COMPLIANT' }}

    - name: Check CIS 1.6 - IPv6 Disabled in sysctl.conf
      shell: |
        grep '^net.ipv6.conf.all.disable_ipv6=1' /etc/sysctl.conf && \
        grep '^net.ipv6.conf.default.disable_ipv6=1' /etc/sysctl.conf && \
        grep '^net.ipv6.conf.lo.disable_ipv6=1' /etc/sysctl.conf || echo "NOT SET"
      register: ipv6_disable
      changed_when: false

    - name: Report IPv6 compliance
      debug:
        msg: >
          CIS 1.6 - IPv6 Disabled: {{ '✅ COMPLIANT' if 'disable_ipv6=1' in ipv6_disable.stdout else '❌ NOT COMPLIANT' }}

    - name: Check CIS 1.11 - PermitRootLogin
      shell: grep '^PermitRootLogin no' /etc/ssh/sshd_config || echo "NOT SET"
      register: root_login
      changed_when: false

    - name: Report Root Login compliance
      debug:
        msg: >
          CIS 1.11 - PermitRootLogin Disabled: {{ '✅ COMPLIANT' if 'PermitRootLogin no' in root_login.stdout else '❌ NOT COMPLIANT' }}
