---
- name: CIS Benchmark Audit - Cloud Linux Instance
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: CIS 1.1.1 - Ensure SSH Banner is configured
      shell: grep '^Banner /etc/issue.net' /etc/ssh/sshd_config || echo "NOT SET"
      register: ssh_banner
      changed_when: false

    - name: Report SSH Banner compliance
      debug:
        msg: >
          CIS 1.1.1 - SSH Banner: {{ '✅ COMPLIANT' if 'Banner /etc/issue.net' in ssh_banner.stdout else '❌ NOT COMPLIANT' }}

    - name: CIS 1.3.1 - Ensure /etc/motd is configured
      shell: test -s /etc/motd && echo "SET" || echo "NOT SET"
      register: motd
      changed_when: false

    - name: Report MOTD compliance
      debug:
        msg: >
          CIS 1.3.1 - MOTD: {{ '✅ COMPLIANT' if 'SET' in motd.stdout else '❌ NOT COMPLIANT' }}

    - name: CIS 3.1.1 - Ensure IP forwarding is disabled
      shell: grep '^net.ipv4.ip_forward = 0' /etc/sysctl.conf || echo "NOT SET"
      register: ip_forward
      changed_when: false

    - name: Report IP forwarding compliance
      debug:
        msg: >
          CIS 3.1.1 - IP Forwarding: {{ '✅ COMPLIANT' if 'net.ipv4.ip_forward = 0' in ip_forward.stdout else '❌ NOT COMPLIANT' }}

    - name: CIS 4.1.1.1 - Ensure auditd is installed
      shell: which auditctl || echo "NOT INSTALLED"
      register: auditd
      changed_when: false

    - name: Report auditd presence
      debug:
        msg: >
          CIS 4.1.1.1 - auditd Installed: {{ '✅ COMPLIANT' if 'auditctl' in auditd.stdout else '❌ NOT COMPLIANT' }}

    - name: CIS 5.2.4 - Ensure SSH root login is disabled
      shell: grep '^PermitRootLogin no' /etc/ssh/sshd_config || echo "NOT SET"
      register: root_login
      changed_when: false

    - name: Report SSH root login compliance
      debug:
        msg: >
          CIS 5.2.4 - Root Login Disabled: {{ '✅ COMPLIANT' if 'PermitRootLogin no' in root_login.stdout else '❌ NOT COMPLIANT' }}

    - name: CIS 5.2.5 - Ensure SSH log level is appropriate
      shell: grep '^LogLevel VERBOSE' /etc/ssh/sshd_config || echo "NOT SET"
      register: ssh_log_level
      changed_when: false

    - name: Report SSH LogLevel compliance
      debug:
        msg: >
          CIS 5.2.5 - LogLevel VERBOSE: {{ '✅ COMPLIANT' if 'LogLevel VERBOSE' in ssh_log_level.stdout else '❌ NOT COMPLIANT' }}

    - name: CIS 6.1.10 - Ensure no world writable files exist
      shell: find / -xdev -type f -perm -0002 -print 2>/dev/null | wc -l
      register: world_writable
      changed_when: false

    - name: Report world writable files
      debug:
        msg: >
          CIS 6.1.10 - World Writable Files: {{ '✅ COMPLIANT' if world_writable.stdout|int == 0 else '❌ FOUND ' ~ world_writable.stdout ~ ' files' }}

