---
- name: Minimal CIS Hardening for Cloud Ubuntu Server
  hosts: cloud_vms
  become: yes

  tasks:
    - name: Disable root SSH login (CIS 5.2.8)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"

    - name: Set SSH protocol to 2 (CIS 5.2.2)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^Protocol"
        line: "Protocol 2"

    - name: Ensure auditd is installed (CIS 4.1.1.1)
      apt:
        name: auditd
        state: present
        update_cache: yes

    - name: Restart SSH service to apply changes
      service:
        name: ssh
        state: restarted
