---
- name: CIS Baseline Hardening for Cloud Ubuntu Server
  hosts: cloud_vms
  become: yes
  vars:
    cis_sshd_config: /etc/ssh/sshd_config

  tasks:
    - name: Ensure UFW is installed (CIS 3.5.1)
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Ensure UFW is enabled (CIS 3.5.2)
      ufw:
        state: enabled

    - name: Set UFW default incoming policy to deny (CIS 3.5.3)
      ufw:
        direction: incoming
        policy: deny

    - name: Set UFW default outgoing policy to allow (CIS 3.5.4)
      ufw:
        direction: outgoing
        policy: allow

    - name: Ensure permissions on /etc/passwd are configured (CIS 6.1.2)
      file:
        path: /etc/passwd
        owner: root
        group: root
        mode: "0644"

    - name: Ensure permissions on /etc/shadow are configured (CIS 6.1.3)
      file:
        path: /etc/shadow
        owner: root
        group: shadow
        mode: "0640"

    - name: Ensure permissions on /etc/group are configured (CIS 6.1.4)
      file:
        path: /etc/group
        owner: root
        group: root
        mode: "0644"

    - name: Disable root SSH login (CIS 5.2.8)
      lineinfile:
        path: "{{ cis_sshd_config }}"
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"

    - name: Ensure SSH protocol is set to 2 (CIS 5.2.2)
      lineinfile:
        path: "{{ cis_sshd_config }}"
        regexp: "^Protocol"
        line: "Protocol 2"

    - name: Disable empty passwords in SSH (CIS 5.2.9)
      lineinfile:
        path: "{{ cis_sshd_config }}"
        regexp: "^PermitEmptyPasswords"
        line: "PermitEmptyPasswords no"

    - name: Set SSH idle timeout interval (CIS 5.2.13)
      blockinfile:
        path: "{{ cis_sshd_config }}"
        block: |
          ClientAliveInterval 300
          ClientAliveCountMax 0

    - name: Restart SSHD to apply changes
      service:
        name: ssh
        state: restarted

    - name: Ensure auditd is installed (CIS 4.1.1.1)
      apt:
        name: auditd
        state: present

    - name: Ensure auditd service is enabled and running
      service:
        name: auditd
        enabled: yes
        state: started
